### ISSUE TITLE
Problem no showing the node

### ISSUE THREAD

**Issue by fayeyen** [Janamou/firebase-demo#2]
The sign in work, and can see the node added in firebase database. Images also upload successfully in storage. 
One thing is not work, NOT showing anything added. on website.
I think is line 50 in index.html
 <div id="notes" class="mdl-grid"></div>
not sure, I'm new to dart.

**Comment by fayeyen** [comment]
Any help?

**Comment by fayeyen** [comment]
Not many people using dart

**Comment by fayeyen** [comment]
OK, I found the reason just set the database rules in firebase
".read": true,

**Comment by Janamou** [comment]
Hi @fayeyen,
I am sorry for my delay. I am happy that it works for you now!
